name: tic_tac_toe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #State
  flutter_bloc: ^8.1.3

  
  #Firebase
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0


  #Utility
  google_fonts: ^6.1.0
  logger: ^2.0.2+1
  easy_logger: ^0.0.2

  #Core
  equatable: ^2.0.5
  get_it: ^7.6.4

   #Navigation
  auto_route: ^7.8.4

  # Config
  easy_localization: ^3.0.3
  #WidgetHelper

  flutter_colorpicker: ^1.0.3

  widgets:
    path: module/widgets

  # Modules
 # gen:
 #   path: module/gen
 # common:
 #   path: module/common
  #core:
  #  path: module/core


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asset/translations/