// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaVj_uajsDYFCZ6bnHw4KOEd8z10VIRw',
    appId: '1:744076678100:web:9215529cef6fbc8843bc41',
    messagingSenderId: '744076678100',
    projectId: 'codeway-1ffe0',
    authDomain: 'codeway-1ffe0.firebaseapp.com',
    storageBucket: 'codeway-1ffe0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNa3eubf_t2MWiyMN9dUgzl1C85cyVREA',
    appId: '1:744076678100:android:cd0c868b416e2b6643bc41',
    messagingSenderId: '744076678100',
    projectId: 'codeway-1ffe0',
    storageBucket: 'codeway-1ffe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KP34yq4zF8wrwVVehVvrZWXz04hdvYY',
    appId: '1:744076678100:ios:bf1b436961756e2d43bc41',
    messagingSenderId: '744076678100',
    projectId: 'codeway-1ffe0',
    storageBucket: 'codeway-1ffe0.appspot.com',
    iosBundleId: 'com.example.codeway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6KP34yq4zF8wrwVVehVvrZWXz04hdvYY',
    appId: '1:744076678100:ios:bf1b436961756e2d43bc41',
    messagingSenderId: '744076678100',
    projectId: 'codeway-1ffe0',
    storageBucket: 'codeway-1ffe0.appspot.com',
    iosBundleId: 'com.example.codeway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEaVj_uajsDYFCZ6bnHw4KOEd8z10VIRw',
    appId: '1:744076678100:web:8e1b0bcaf61476af43bc41',
    messagingSenderId: '744076678100',
    projectId: 'codeway-1ffe0',
    authDomain: 'codeway-1ffe0.firebaseapp.com',
    storageBucket: 'codeway-1ffe0.appspot.com',
  );
}
